### PR TITLE
Updated data input format; Changed analysis to handle single assay case

### PR DESCRIPTION
**Pull request by k-t-to**
Changed data import format from wide to long. 
Analysis is now performed on data for a single sample assay 
Tests have been updated for the new input file format

All helper functions are now internal - only calculate_pod_quantiles can be called after installation. Functions used for pod estimation have been consolidated to a single file.

### CODE REVIEW

**Comment by k-t-to** [comment]
Another major change: Updated analysis to run on log-transformed data. Will return POD estimates on original dose scale.

**Comment by k-t-to** [comment]
Please advise: gravee only returns the requested POD quantiles. Should we have it return the full vector of POD estimates as well?

**Comment by DataSciBurgoon** [comment]
As a user I could see having the full vector being useful (and probably a
feature request sooner than later).

**Comment by k-t-to** [comment]
updated output to list with pod vector and pod quantiles

**Review by DataSciBurgoon — APPROVED** [review]

**Comment by DataSciBurgoon** [comment]
Looks good to me. Make sure your tests work, and I'd say merge.

**Pull request merged**
